/**
 * Runs after `vite build` (see package.json):
 *  1. Removes the __data.json files SvelteKit prerenders for server loads. The site ships no
 *     client JavaScript (csr = false), so nothing ever requests them.
 *  2. Writes host redirect files with real 301 redirects for the old page names
 *     (src/lib/legacy.json): `.htaccess` for Apache, `_redirects` for Netlify/Cloudflare Pages.
 *     The meta-refresh pages (e.g. build/kontakt.html) remain as a fallback for other hosts.
 */
import { readFileSync, readdirSync, rmSync, rmdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const BUILD = 'build';

function clean(dir) {
	for (const name of readdirSync(dir)) {
		const path = join(dir, name);
		if (statSync(path).isDirectory()) {
			clean(path);
			if (readdirSync(path).length === 0) rmdirSync(path);
		} else if (name === '__data.json') {
			rmSync(path);
		}
	}
}
clean(BUILD);

const legacy = JSON.parse(readFileSync('src/lib/legacy.json', 'utf8'));
const entries = Object.entries(legacy);

writeFileSync(
	join(BUILD, '_redirects'),
	entries.map(([from, to]) => `/${from} ${to} 301`).join('\n') + '\n'
);
writeFileSync(
	join(BUILD, '.htaccess'),
	[
		'# Generated by scripts/postbuild.js',
		'ErrorDocument 404 /404.html',
		...entries.map(([from, to]) => `Redirect 301 /${from} ${to}`)
	].join('\n') + '\n'
);
